// <auto-generated />
namespace CRUD_EntityFramework_Ti32.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class banco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(banco));
        
        string IMigrationMetadata.Id
        {
            get { return "202010070014447_banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
